### ISSUE TITLE
/api/ingest/ response

### ISSUE THREAD

**Issue by matee911** [matee911/ClayPipe#11]
Should it be JSON with `status=<int>` or just a HTTP Status Code?

**Comment by matee911** [comment]
Please also look at:

* Update - PATCH /api/message/{messageId}
* Delete - DELETE /api/message/{messageId}
* Resend - POST /api/message/{messageId}

**Comment by ekamil** [comment]
That's more general. If we want to include status codes in the body we
should always use envelopes with the status and a message body with, err,
body. Also we would need to think about and document all the error codes we
use.
Imho there's no need for that. Let's just incorporate http status codes
into the API and omit body.
The only exception would be PATCH. If, during the front-end dev, the flow
patch+get became frequent it'd be better to return the message along the
http200 code.

**Comment by matee911** [comment]
@ekamil could you amend the API documentation?

**Comment by matee911** [comment]
bump @ekamil
